server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.141.51.79:5003
management:
  endpoints:
    web:
      exposure:
        include: "*"