server:
  port: 80

spring:
  application:
    name: hystrix-order
eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    #    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka  #单机版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版

feign:
  hystrix:
    enabled: true

  compression:
    request:
      enabled: true #开启请求压缩
      #最小出发压缩的大小
      min-request-size: 2048
      #触发压缩的数据类型
      mime-types: text/xml, application/xml, application/json
    response:
      enabled: true

logging:
  level:
    com.george.springcloud.service: debug